#!/bin/bash

nohup ./xdg-portal-hyprland &
nohup dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
nohup systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
nohup /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nohup swww init &
LC_ALL=en_US.UTF-8 nohup waybar -c $HOME/.config/waybar/config.jsonc -s $HOME/.config/waybar/style.css &
nohup mako &
