#!/bin/bash

function printHelp() { 
    echo """
    static     set a single static colour
    breathe    pulse between one or two colours
    strobe     strobe through all colours
    rainbow    rainbow cycling in one of four directions
    pulse      set a rapid pulse
    """
}

function wrongParam() {
    echo "Wrong use of params\n\n"
    printHelp
}

function changeMode() {
    asusctl led-mode $1
}

function changeKeymap() {
    keymap=$(cat ~/.config/hypr/hyprland.conf | grep "kb_layout =.*" | awk '{print $NF}')
    if [ $keymap == "us" ]; then
        sudo localectl set-keymap --no-convert es
        sed -i '20s/.*/    kb_layout = es/' ~/.config/hypr/hyprland.conf
    elif [ $keymap == "es" ]; then
        sudo localectl set-keymap --no-convert us
        sed -i '20s/.*/    kb_layout = us/' ~/.config/hypr/hyprland.conf
    else
        sudo localectl set-keymap --no-convert es
        sed -i '20s/.*/    kb_layout = es/' ~/.config/hypr/hyprland.conf
    fi
}

case $1 in 
    -h | --help | "" )
        printHelp
    ;;

    static | breathe | strobe | rainbow | pulse )
        changeMode $1
    ;;

    --altkeymap )
        changeKeymap
    ;;

    * )
        wrongParam
    ;;
esac

exit 0