#!/bin/bash

curr_background=$(swww query | awk '{print $NF}'  | tr "/" " " | awk '{print $NF}')
background_dir="/home/atenea/Pictures/background"
background_list=$(ls $background_dir)
last=$(echo $background_list | awk '{print $NF}')
first=$(echo $background_list | awk '{print $1}')
new_bg=
found=0

function applyBg() {
    new_bg=$background_dir
    new_bg+="/"
    new_bg+=$1
    swww img $new_bg --transition-duration 2 --transition-type grow --transition-fps 240 --transition-pos $(hyprctl cursorpos | awk '{print $1 $2}') --invert-y
}


if [ $curr_background == $last ]; then
    applyBg $first
    exit 0
fi

for it in $background_list; do
    if [ $it == $curr_background ]; then
        found=1
        continue
    fi
    if [ $found == 1 ]; then
        applyBg $it
        break
    fi
done

exit 0
