#!/bin/bash

curr_background=$(swww query | awk '{print $NF}'  | tr "/" " " | awk '{print $NF}')
background_dir="/home/atenea/Pictures/background"
background_list=$(ls $background_dir)
last=$(echo $background_list | awk '{print $NF}')
first=$(echo $background_list | awk '{print $1}')

found=false
for it in $background_list; do 
: << COMMENT
    if [ $it == $curr_background ]; then
        $found = true
        #echo $it
        continue;
    fi
    if [ $found ]; then
        new_bg=$background_dir
        new_bg+="/"
        new_bg+=$it
        swww img $new_bg --transition-type grow --transition-fps 144 --transition-pos $(hyprctl cursorpos | awk '{print $1 $2}') --invert-y
        break;
    fi
    if [ $it == $last ]; then
        swww img $first --transition-type grow --transition-fps 144 --transition-pos $(hyprctl cursorpos | awk '{print $1 $2}') --invert-y
        break;
    fi
COMMENT
    echo $it
    
done

exit 0