#!/bin/bash

pgrep waybar > /dev/null 2>&1
if [ $? -eq 0 ]; then
    killall waybar > /dev/null 2>&1
fi

waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css > /dev/null 2>&1 & disown