#!/bin/bash

cp -r ~/.config/{hypr,kitty,starship.toml,waybar,lvim} ~/Github/arch-linux-guide/config/
cp ~/.bashrc ~/.bash_aliases ~/.bash_pfetch ~/Github/arch-linux-guide/home/
cp ~/Scripts/* ~/Github/arch-linux-guide/scripts
sleep 0.2
echo "[+] Files copied succesfully"
sleep 0.2
ps aux | pgrep github-desktop 2>&1 1> /dev/null
if ! [ $? -eq 0 ]; then
    echo "[+] Openning github-desktop"
    exec github-desktop 2> /dev/null 1> /dev/null & disown
    sleep 1.75
fi
echo "[+] Program terminated!"
