#!/bin/bash

battery=
volume=
brightness=
private_ip=
public_ip=
keymap=
date=

function getBattery() {
    battery=$(cat /sys/class/power_supply/BAT0/capacity)
    echo "   $battery%"
}

function getSound() {
    volume=$(pactl list sinks | grep "Volume: front-left" | awk '{printf  $5}')
    echo "   $volume"
}

function getBrightness() {
    brightness=$(brightnessctl g)
    echo "   $brightness%"
}

function getIp() {
    private_ip=$(hostname -i)
    public_ip=$(curl -s ifconfig.me)
    echo "   $private_ip | $public_ip"
}

function getKeymap() {
    keymap=$(cat ~/.config/hypr/hyprland.conf | grep "kb_layout =.*" | awk '{printf $NF}')
    echo "   $keymap"
}

function getDate() {
    date=$(date)
    echo "   $date"
}  

function getAll() {
    echo -n "   Battery:      "
    getBattery
    echo -n "   Volume:       "
    getSound
    echo -n "   Brightness:   "
    getBrightness
    echo -n "   Ip:           "
    getIp
    echo -n "   Keymap:       "
    getKeymap
}  

function printHelp() {
    echo """
    -h  | --help
    -b  | --battery
    -s  | --sound
    -br | --brightness
    -i  | --ip
    -k  | --keymap
    -a  | --all
    """
}

function wrongParam() {
    echo -e "   Wrong use of params\\n\\n"
    printHelp
}

echo ""
case $1 in 
    -h | --help | "" )
        printHelp
    ;;

    -b | --battery )
        getBattery
    ;;

    -s | --sound )
        getSound
    ;;

    -br | --brightness )
        getBrightness
    ;;

    -i | --ip )
        getIp
    ;;

    -d | --date )
        getDate
    ;;

    -k | --keymap )
        getKeymap
    ;;

    -a | --all )
        getAll
    ;;

    * )
        wrongParam
    ;;
esac

exit 0